function sortMetadata(tabMetadata){
    let sortTab = tabMetadata.map(elt =>{
        return elt.metadata;
    })
    sortTab.sort();
    let newTab = sortTab.map(element =>{
        let index = tabMetadata.findIndex(elt => elt.metadata == element);
        return{
            "metadata": element,
            "Name": tabMetadata[index].Name,
            "IsSearchable" : tabMetadata[index].IsSearchable
        }
    })
    return newTab;
}

const metadataTab = [
    {metadata: 'AIApplication', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'AIApplicationConfig', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'AnimationRule', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'EntityDefinition', Name: 'QualifiedApiName',IsSearchable: false},
    {metadata: 'ApexClass', Name: 'Name',IsSearchable: true},
    {metadata: 'CustomObject', Name: 'DeveloperName',IsSearchable: true},
    {metadata: 'ApexComponent', Name: 'Name',IsSearchable: true},
    {metadata: 'ApexPage', Name: 'Name',IsSearchable: true},
    {metadata: 'ApexTestSuite', Name: 'TestSuiteName',IsSearchable: false},
    {metadata: 'Flow', Name: 'MasterLabel',IsSearchable: false},
    {metadata: 'ValidationRule', Name: 'ValidationName',IsSearchable: false},
    {metadata: 'WorkflowTask', Name: 'Subject',IsSearchable: true},
    {metadata: 'ApexTrigger', Name: 'Name',IsSearchable: true},
    {metadata: 'AssignmentRule', Name: 'Name',IsSearchable: true},
    {metadata: 'AuraDefinitionBundle', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'AutoResponseRule', Name: 'Name',IsSearchable: false},
    {metadata: 'BrandingSet', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'BusinessProcess', Name: 'Name',IsSearchable: false},
    {metadata: 'CMSConnectSource', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'Certificate', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'ChannelLayout', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'CleanDataService', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'CommunityTemplateDefinition', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'CommunityThemeDefinition', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'CompactLayout', Name: 'DeveloperName',IsSearchable: true},
    {metadata: 'CustomApplication', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'CustomField', Name: 'DeveloperName',IsSearchable: true},
    {metadata: 'CustomHelpMenuSection', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'CustomLabel', Name: 'Name',IsSearchable: false},
    {metadata: 'CustomTab', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'Document', Name: 'DeveloperName',IsSearchable: true},
    {metadata: 'EmailTemplate', Name: 'Name',IsSearchable: true},
    {metadata: 'EmbeddedServiceBranding', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'EmbeddedServiceConfig', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'EmbeddedServiceFlowConfig', Name: 'Enabled',IsSearchable: true},
    {metadata: 'EmbeddedServiceMenuSettings', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'ExternalCredential', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'ExternalDataSource', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'ExternalDataSrcDescriptor', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'ExternalServiceRegistration', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'FieldRestrictionRule', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'FlexiPage', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'FlowCategory', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'FlowDefinition', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'FlowTest', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'GlobalValueSet', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'Group', Name: 'DeveloperName',IsSearchable: true},
    {metadata: 'HomePageComponent', Name: 'Name',IsSearchable: true},
    {metadata: 'HomePageLayout', Name: 'Name',IsSearchable: true},
    {metadata: 'IPAddressRange', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'InboundNetworkConnection', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'Index', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'KeywordList', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'Layout', Name: 'Name',IsSearchable: false},
    {metadata: 'LeadConvertSettings', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'LightningBolt', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'LightningComponentBundle', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'LightningExperienceTheme', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'LightningMessageChannel', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'LightningOnboardingConfig', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'MLDataDefinition', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'MLPredictionDefinition', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'MLRecommendationDefinition', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'ManagedContentType', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'ModerationRule', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'NamedCredential', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'OutboundNetworkConnection', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'PathAssistant', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'PaymentGatewayProvider', Name: 'DeveloperName',IsSearchable: true},
    {metadata: 'PermissionSet', Name: 'Name',IsSearchable: true},
    {metadata: 'PermissionSetGroup', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'PlatformEventChannel', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'PlatformCachePartition', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'PlatformEventChannelMember', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'PlatformEventSubscriberConfig', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'PostTemplate', Name: 'Name',IsSearchable: true},
    {metadata: 'Profile', Name: 'Name',IsSearchable: true},
    {metadata: 'Prompt', Name: 'DeveloperName',IsSearchable: true},
    {metadata: 'RecommendationStrategy', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'RecordActionDeployment', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'RecordType', Name: 'Name',IsSearchable: false},
    {metadata: 'RestrictionRule', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'Role', Name: 'DeveloperName',IsSearchable: true},
    {metadata: 'Scontrol', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'StaticResource', Name: 'Name',IsSearchable: true},
    {metadata: 'UserCriteria', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'UserProfileSearchScope', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'UserProvisioningConfig', Name: 'DeveloperName',IsSearchable: false},
    {metadata: 'WebLink', Name: 'Name',IsSearchable: true},
    {metadata: 'WorkflowAlert', Name: 'DeveloperName',IsSearchable: true},
    {metadata: 'WorkflowFieldUpdate', Name: 'Name',IsSearchable: true},
    {metadata: 'WorkflowOutboundMessage', Name: 'Name',IsSearchable: true},
    {metadata: 'WorkflowRule', Name: 'Name',IsSearchable: true}
]



export default sortMetadata(metadataTab);